### ISSUE TITLE
Blank screen on starting 

### ISSUE THREAD

**Issue by saurabhvyas** [blacksonic/angular2-esnext-starter#12]
I installed everything as given in tutorial then I  ran the command node server/index.js and in temrinal it said running on port 9000,but it gives me an empty blank page

**Comment by blacksonic** [comment]
Can you share some details?
Console output, node version, operating system etc

**Comment by joe-singer** [comment]
I am having the same issue. The server serves the index.html in dist/client, but cannot find vendor.js and other files.

Windows 7 pro
Node version 5.7.0

![issue](https://cloud.githubusercontent.com/assets/902009/14830215/5f0a0e82-0ba4-11e6-8edc-25d3ca4b5912.png)

**Comment by blacksonic** [comment]
You started the app with ```gulp serve```?
What is inside the dist folder?

**Comment by joe-singer** [comment]
I started with gulp serve

Dist folder:
```
\---client
    |   angular.ico
    |   boot.css
    |   boot.js
    |   boot.js.map
    |   index.html
    |   vendor.js
    |   vendor.js.map
    |   
    \---css
            about.css
```

**Comment by blacksonic** [comment]
That seems fine, the gulp task generates the files.
Can you check what is the static file path what is generated on the server?
```server/config.js```

**Comment by joe-singer** [comment]
`config.staticPath = C:\Users\jsinger\Desktop\angular2-es6-starter\dist\client`

**Comment by blacksonic** [comment]
that one also seems right

**Comment by joe-singer** [comment]
Found the issue: https://github.com/koajs/static/issues/78
Needed to upgrade Node to 5.71 or later.

**Comment by blacksonic** [comment]
I'm runnig Node 5.10.1, that is why mine was working fine.
