### ISSUE TITLE
Annotation is not es6

### ISSUE THREAD

**Issue by FBerthelot** [blacksonic/angular2-esnext-starter#13]
I create this issue just to notice you that decorator is not es6 😄 

You can do things like this : 
```javascript
export const AppComponent = Component({
        selector: 'my-app',
        template: '<h1>My Angular 2 App in true es6</h1>'
    })
    .Class({
        constructor: function() {}
    });
```
Maybe there is better and more beautiful way to avoid annotation, but didn't find it yet 😃

**Comment by blacksonic** [comment]
Yes i know.
Is there a way to make a redirect for the old name if i rename the repository for example angular2-esnext-starter?

**Comment by blacksonic** [comment]
Yaaay it works out of the box
https://github.com/blog/1508-repository-redirects-are-here

**Comment by FBerthelot** [comment]
Yes, github do it automatically ;)
But not npm nor bower.

**Comment by blacksonic** [comment]
It is not published there so it can work.

**Comment by blacksonic** [comment]
Renamed the repo to esnext, now time to update the external links.
