### ISSUE TITLE
Perhaps two starters, not everyone uses node on the backend

### ISSUE THREAD

**Issue by niemyjski** [blacksonic/angular2-esnext-starter#15]
This sample assumes I'll have a client and server written both in js. For a large number of users this is not the case.

**Comment by blacksonic** [comment]
The minimal backend is needed to validate the JWT token and store plus modify the list of posts. It cant be done on the client.
It is so minimal i think you can easily ditch it to something else. With a backend in another language would make this example app more complicated.

And yes for a frontend only i would make a different repository, but in that case authentication should be solved with a provider like Auth0 and the storage of posts with Firebase.

**Comment by niemyjski** [comment]
I'm saying make a port that doesn't have the jwt stuff at all and maybe only a src folder (no client and server folder) thus removing code and making the sample more like real world spa apps that don't use node.

**Comment by blacksonic** [comment]
My [TodoMVC repository](https://github.com/blacksonic/angular2-esnext-todomvc) now shows a minimal setup without server side and gulp tasks.
