### ISSUE TITLE
Browser back button not working

### ISSUE THREAD

**Issue by abacaj** [blacksonic/angular2-esnext-starter#16]
On Chrome clicking `New Post` and then trying to press the back button does not bring you back to the homepage - is this intended?

**Comment by blacksonic** [comment]
Does it happen when you are logged out and click on new post?
If so it is not intended, but when you hit the back button, you navigate to an authorized url (new post), which is redirected to the login page because of being unauthorized.

**Comment by blacksonic** [comment]
the new post button is no longer available in logged out state, and also there is no navigation if it cant activate it, so it wont happen with this setup
