### ISSUE TITLE
How to use i18n ?

### ISSUE THREAD

**Issue by Darshan-popin** [blacksonic/angular2-esnext-starter#20]
i was couldn't able to figure out on how the i18n works in the angular2-esnext-starter,.. 
Currently i'm trying with angular 2 ES6 for multi language app,.. can you please suggest on how could i achieve it using you're method in i18n/index.js file,..

**Comment by blacksonic** [comment]
Currently it is only usable with angular2-translate, I'll readd it to the project

**Comment by Darshan-popin** [comment]
Thank you ,.. Will look forward to it

**Comment by blacksonic** [comment]
I have reenabled it, look at ```AppComponent``` and ```MenuComponent``` for usage
